
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          144339
     no. of nonzeroes in lower triangle of a =         4167147
     no. of nonzeroes in the factor l        =        19748964
     ratio of nonzeroes in factor (min/max)  =          0.8675
     number of super nodes                   =            6501
     maximum order of a front matrix         =            1035
     maximum size of a front matrix          =          536130
     maximum size of a front trapezoid       =          284004
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      3.7928D+09
     no. of floating point ops for solve     =      3.5141D+08
     ratio of flops for factor (min/max)     =          0.8952
     ratio of allocated memory (max/min)     =          1.1366
     number of positive pivots               =          144339
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        369846.        3. MB
                95-   1        360448.        3. MB        341091.        3. MB
                95-   2        393216.        3. MB        389988.        3. MB
                95-   3        425984.        3. MB        400977.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1572864.       12. MB       1501902.       11. MB


  Solver Memory allocated on core    0       =       89.736 MB
  Solver Memory allocated on core    1       =       84.222 MB
  Solver Memory allocated on core    2       =       94.435 MB
  Solver Memory allocated on core    3       =       95.730 MB
  Total Solver Memory allocated by all cores =      364.123 MB

