#!/bin/bash
#PBS -N optimize_tile_gnn
#PBS -l select=1:ncpus=96:mem=70gb:host=aluf5
#PBS -l walltime=24:00:00
#PBS -q long_q

cd /home/ryonatan/projects/ai_fea_surrogate
source env/bin/activate

rm -r optimization/artifacts/*
rm -r optimization/screenshots/* 
rm -r data/hollow_cube/Instance_*
rm -r data/hollow_cube/ansys_*

pkill -u $USER -f ansys251 || true
sleep 5

export OMP_NUM_THREADS=4
export MKL_NUM_THREADS=4
export PYTHONUNBUFFERED=1

#mkdir -p optimization/artifacts optimization/screenshots

python -u -m optimization.optimize_dims \
    --geometry hollow_cube \
    --arch mapdl \
    --optimizer cma \
    --generations 10000 \
    --pop_size 30 \
    --search_space reflect \
    --sigma0 0.4 \
    --constraint_mode quadratic \
    --processes 16 \
    --batch_size 10 \
    --reset_on_stagnation \
    --max_unproductive_resets 5 \
    > ${PBS_O_WORKDIR}/run_${PBS_JOBID}.log 2>&1

rm -r data/hollow_cube/Instance_*
rm -r data/hollow_cube/ansys_*
