#!/bin/bash

#PBS -N stress_param_sweep
#PBS -l select=1:ncpus=96:mem=70gb:host=aluf5
#PBS -l walltime=24:00:00
#PBS -q long_q

pkill -u $USER -f ansys251 || true

cd /home/ryonatan/projects/ai_fea_surrogate
source env/bin/activate

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export PYTHONUNBUFFERED=1

python -u -m analysis.stress_param_sweep > ${PBS_O_WORKDIR}/run_${PBS_JOBID}.log 2>&1

rm -rf data/bistable/Instance_*
rm -rf data/bistable/ansys_*
