#!/bin/bash
#PBS -N train_model
#PBS -l select=1:ncpus=16:mem=32gb
#PBS -l walltime=12:00:00
#PBS -q long_q

cd $PBS_O_WORKDIR
source env/bin/activate

export OMP_NUM_THREADS=16
export MKL_NUM_THREADS=16
export PYTHONUNBUFFERED=1


python -u -m training.gnn_training \
    --geometry hollow_cube \
    --num_samples 3000 \
    --epochs 200 \
    --lr 2e-3 \
    --batch_size 8 \
    --hidden_dim 128 \
    --conv_layers 6 \
    > ${PBS_O_WORKDIR}/hc_train_${PBS_JOBID}.log 2>&1

M