
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          144339
     no. of nonzeroes in lower triangle of a =         4167147
     no. of nonzeroes in the factor l        =        19691531
     ratio of nonzeroes in factor (min/max)  =          0.9423
     number of super nodes                   =            6502
     maximum order of a front matrix         =             882
     maximum size of a front matrix          =          389403
     maximum size of a front trapezoid       =          217710
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      3.7203D+09
     no. of floating point ops for solve     =      3.5224D+08
     ratio of flops for factor (min/max)     =          0.8782
     ratio of allocated memory (max/min)     =          1.0711
     number of positive pivots               =          144339
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        425984.        3. MB        394755.        3. MB
                95-   1        393216.        3. MB        360457.        3. MB
                95-   2        393216.        3. MB        368820.        3. MB
                95-   3        393216.        3. MB        373992.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1605632.       12. MB       1498024.       11. MB


  Solver Memory allocated on core    0       =       94.780 MB
  Solver Memory allocated on core    1       =       88.490 MB
  Solver Memory allocated on core    2       =       89.510 MB
  Solver Memory allocated on core    3       =       90.135 MB
  Total Solver Memory allocated by all cores =      362.915 MB

