
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          144339
     no. of nonzeroes in lower triangle of a =         4167147
     no. of nonzeroes in the factor l        =        19703045
     ratio of nonzeroes in factor (min/max)  =          0.8523
     number of super nodes                   =            6510
     maximum order of a front matrix         =             810
     maximum size of a front matrix          =          328455
     maximum size of a front trapezoid       =          246240
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      3.7259D+09
     no. of floating point ops for solve     =      3.4994D+08
     ratio of flops for factor (min/max)     =          0.8209
     ratio of allocated memory (max/min)     =          1.1325
     number of positive pivots               =          144339
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        361109.        3. MB
                95-   1        360448.        3. MB        348404.        3. MB
                95-   2        425984.        3. MB        402127.        3. MB
                95-   3        393216.        3. MB        389114.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1572864.       12. MB       1500754.       11. MB


  Solver Memory allocated on core    0       =       88.033 MB
  Solver Memory allocated on core    1       =       85.284 MB
  Solver Memory allocated on core    2       =       96.585 MB
  Solver Memory allocated on core    3       =       93.123 MB
  Total Solver Memory allocated by all cores =      363.025 MB

