
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          144339
     no. of nonzeroes in lower triangle of a =         4167147
     no. of nonzeroes in the factor l        =        19562444
     ratio of nonzeroes in factor (min/max)  =          0.9393
     number of super nodes                   =            6499
     maximum order of a front matrix         =             774
     maximum size of a front matrix          =          299925
     maximum size of a front trapezoid       =          203931
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      3.5894D+09
     no. of floating point ops for solve     =      1.4016D+08
     ratio of flops for factor (min/max)     =          0.9151
     ratio of allocated memory (max/min)     =          1.0520
     number of positive pivots               =          144339
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        378928.        3. MB
                95-   1        393216.        3. MB        360837.        3. MB
                95-   2        393216.        3. MB        378659.        3. MB
                95-   3        393216.        3. MB        376387.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1572864.       12. MB       1494811.       11. MB


  Solver Memory allocated on core    0       =       91.506 MB
  Solver Memory allocated on core    1       =       87.616 MB
  Solver Memory allocated on core    2       =       92.174 MB
  Solver Memory allocated on core    3       =       90.540 MB
  Total Solver Memory allocated by all cores =      361.837 MB

