
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          144339
     no. of nonzeroes in lower triangle of a =         4167147
     no. of nonzeroes in the factor l        =        19646562
     ratio of nonzeroes in factor (min/max)  =          0.8537
     number of super nodes                   =            6499
     maximum order of a front matrix         =             810
     maximum size of a front matrix          =          328455
     maximum size of a front trapezoid       =          231813
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      3.6094D+09
     no. of floating point ops for solve     =      3.5184D+08
     ratio of flops for factor (min/max)     =          0.8837
     ratio of allocated memory (max/min)     =          1.1509
     number of positive pivots               =          144339
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        425984.        3. MB        408935.        3. MB
                95-   1        393216.        3. MB        381946.        3. MB
                95-   2        360448.        3. MB        360028.        3. MB
                95-   3        360448.        3. MB        349438.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1540096.       12. MB       1500347.       11. MB


  Solver Memory allocated on core    0       =       97.370 MB
  Solver Memory allocated on core    1       =       92.634 MB
  Solver Memory allocated on core    2       =       87.958 MB
  Solver Memory allocated on core    3       =       84.600 MB
  Total Solver Memory allocated by all cores =      362.562 MB

