
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          144339
     no. of nonzeroes in lower triangle of a =         4167147
     no. of nonzeroes in the factor l        =        19640403
     ratio of nonzeroes in factor (min/max)  =          0.7996
     number of super nodes                   =            6474
     maximum order of a front matrix         =             810
     maximum size of a front matrix          =          328455
     maximum size of a front trapezoid       =          253377
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      3.6439D+09
     no. of floating point ops for solve     =      2.1042D+08
     ratio of flops for factor (min/max)     =          0.7428
     ratio of allocated memory (max/min)     =          1.2104
     number of positive pivots               =          144339
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        359339.        3. MB
                95-   1        360448.        3. MB        335769.        3. MB
                95-   2        425984.        3. MB        420656.        3. MB
                95-   3        393216.        3. MB        378959.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       1540096.       12. MB       1494723.       11. MB


  Solver Memory allocated on core    0       =       87.164 MB
  Solver Memory allocated on core    1       =       82.853 MB
  Solver Memory allocated on core    2       =      100.285 MB
  Solver Memory allocated on core    3       =       93.717 MB
  Total Solver Memory allocated by all cores =      364.020 MB

